### PR TITLE
Allow linking against symbols specified in a .map file

### PR DESCRIPTION
**Pull request by tech-ticks**
Depends on https://github.com/skyline-dev/skyline/pull/50.

Parses a .map file located in `romfs/skyline/maps/main.map` and makes its symbols available in plugins via dynamic linking. I've only tested it with this .map file exported by IDA: https://github.com/tech-ticks/hyperbeam/blob/master/patches/maps/102/main.map, so it's possible and likely that this won't work with .map files exported by other tools.

The main caveat is that only one game version is supported. I would have preferred to load a .map file named after `main`'s build ID (similar to how exefs IPS patches work), but I couldn't find out if it's possible to obtain it with the `nn` SDK. The Homebrew app _Edison_ obtains it with the `libnx` function `ldrDmntGetProcessModuleInfo`, which seems to communicate with a service. I didn't look into it any further.

### CODE REVIEW

**Comment by tech-ticks** [comment]
I've added another commit that fixes odd behaviour in Pokémon Mystery Dungeon Rescue Team DX: The game seems to set its own exception handler (maybe all Unity games do?), which for some reason causes Atmosphère not to generate a crash report on my Switch, but only if Skyline is used (?). I hope the stub doesn't break any other games, but let me know if it causes issues.

**Comment by Raytwo** [comment]
Hey there,

I’ve discussed this with @jam1garner in DMs but I’m not sure the outcome of the discussion was transmitted to you so here goes:
I’m a bit concerned about the way you stubbed out the exception handler setter, as you have now made it so *nobody* can set a custom exception handler, not even modders. Which kinds of ruins my own plan to be perfectly honest! Lol

I’d advice to simply call the method with the default exception handler in your own code plugin, or eventually hooking the method in your plugin directly to not spread this to other games who do not require to have their exception handler forcefully locked.

Let’s try to only do this kind of things when the issue applies to literally every game, or at least not in a way that stops other people from using parts of the SDK.

**Comment by jam1garner** [comment]
> Hey there,
> 
> I’ve discussed this with @jam1garner in DMs but I’m not sure the outcome of the discussion was transmitted to you so here goes:
> I’m a bit concerned about the way you stubbed out the exception handler setter, as you have now made it so *nobody* can set a custom exception handler, not even modders. Which kinds of ruins my own plan to be perfectly honest! Lol
> 
> I’d advice to simply call the method with the default exception handler in your own code plugin, or eventually hooking the method in your plugin directly to not spread this to other games who do not require to have their exception handler forcefully locked.
> 
> Let’s try to only do this kind of things when the issue applies to literally every game, or at least not in a way that stops other people from using parts of the SDK.

I still think a better solution would be to provide a skyline API for setting an exception handler and a function to 'disable' the hook by having it call the original.

Also I don't think "affects every game" is the bar for inclusion either. It's not really constructive, especially in this case where it seems pretty solvable in a way that covers both usecases.

**Comment by Raytwo** [comment]
> Also I don't think "affects every game" is the bar for inclusion either. It's not really constructive, especially in this case where it seems pretty solvable in a way that covers both usecases.

That was only in the context of blocking/breaking an SDK method as a solution to a problem, what I mean by that is that I don't think this kind of things (breaking SDK methods) should be done except if the issue applies to every game.

**Comment by tech-ticks** [comment]
Good point, I didn't really think about plugins that would override the exception handler. I've removed the last commit to do it in a plugin as suggested.

**Comment by tech-ticks** [comment]
Closing this PR since it has become stale and other branches on my fork have diverged pretty far from this state. Might revisit it later.

**Pull request closed without merging**
